/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientWorkArea;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Neelu
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private JPanel container;
    /**
     * Creates new form PatientWorkAreaJPanel
     */
    public PatientWorkAreaJPanel(JPanel c, JPanel upc, UserAccount ua, Organization o, Enterprise e) {
        initComponents();
         userProcessContainer = upc;
        userAccount = ua;
        organization = o;
        enterprise = e;
        container =c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonBookAppointment = new javax.swing.JButton();
        jButtonCheckAppointment = new javax.swing.JButton();
        jButtonCreateProfile = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Patient Work Area");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientWorkArea/patient.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jButtonBookAppointment.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonBookAppointment.setText("Book Appointment");
        jButtonBookAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookAppointmentActionPerformed(evt);
            }
        });

        jButtonCheckAppointment.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonCheckAppointment.setText("Check Appointment");
        jButtonCheckAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckAppointmentActionPerformed(evt);
            }
        });

        jButtonCreateProfile.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonCreateProfile.setText("Update Profile");
        jButtonCreateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonCreateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBookAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCheckAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButtonCreateProfile)
                .addGap(18, 18, 18)
                .addComponent(jButtonBookAppointment)
                .addGap(18, 18, 18)
                .addComponent(jButtonCheckAppointment)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBookAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookAppointmentActionPerformed
        // TODO add your handling code here:
        BookAppointmentJPanel panel = new BookAppointmentJPanel(userProcessContainer, userAccount, organization, enterprise);
        userProcessContainer.add("BookAppointmentJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_jButtonBookAppointmentActionPerformed

    private void jButtonCheckAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckAppointmentActionPerformed
        // TODO add your handling code here:
        CheckStatusJPanel panel = new CheckStatusJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("CheckStatusJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButtonCheckAppointmentActionPerformed

    private void jButtonCreateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateProfileActionPerformed
        // TODO add your handling code here:
        CreateProfileJPanel panel = new CreateProfileJPanel(userProcessContainer, userAccount, organization, enterprise);
        userProcessContainer.add("CreateProfileJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButtonCreateProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBookAppointment;
    private javax.swing.JButton jButtonCheckAppointment;
    private javax.swing.JButton jButtonCreateProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
